Undercolllateralized borrow
omomo-finance/omomo-protocol pull request #203
Opened 2022-08-22 19:47 UTC by dmytro-shash

2022-08-23 12:47 UTC, dmytro-shash commented
прислухався до моделі яку обговорювали раніше  - спочатку все підготувати / перевірити і потім викликати функцію

перевірка чи можливо брати такий uncollateralized borrow для контретного юзера буде на стороні нашого marging contract та відповідна кількість токенів ( * leverage * xrate ) буде реалізована в тасці, яку запланували сьогодні ( на відкриття позиції ).

2022-08-25 20:49 UTC, markblaize requested changes

2022-08-25 20:49 UTC, markblaize commented on contracts/controller/src/borrows_supplies.rs
> +        is_collateralized: bool,
@dmytro-shash in such an approach, anyone could make undercollateralized borrows (which is a critical breach in the protocol).
Also, once something is live interface changes are very unwelcome.

The only thing we actually need is to allow some specific account to make such borrows.

2022-08-26 08:32 UTC, markblaize approved these changes

2022-08-26 08:32 UTC, merged