deposit to market and transfer to mtrading contract | balance handling
omomo-finance/omomo-protocol pull request #204
Opened 2022-08-30 13:24 UTC by dmytro-shash

2022-08-30 14:38 UTC, dmytro-shash commented
![image](https://user-images.githubusercontent.com/97089150/187465770-0eab5954-2832-4f61-a5a0-d6bad22e6503.jpeg)

2022-08-30 14:40 UTC, dmytro-shash commented
загальний флоу юзер депозитить на маркет, де в успішному кейсі якщо все проходить правильно ці токени переводяться на марджин трейдінг контракт, і записується deposits даного юзера

2022-08-31 19:16 UTC, markblaize requested changes

2022-08-31 19:16 UTC, markblaize commented on contracts/dtoken/src/deposit.rs
> +        underlying_token::ft_transfer(
@dmytro-shash, we don't need to transfer tokens to margin trading; it makes no business value in first transferring tokens to the market and then transferring those tokens to another account.

You need to accept the deposit, store the balance somewhere, and provide method to view user balance deposited to the margin trading contract

2022-09-01 11:00 UTC, dmytro-shash commented on contracts/dtoken/src/deposit.rs
> +const MARGIN_TRADING_CONTRACT: &str = "mtrading.omomo-finance.testnet";
agree

2022-09-01 20:38 UTC, merged